language: python
python:
- '2.7'
- '3.4'
- '3.5'
install:
  - pip install --upgrade "setuptools<40.0.0"
  - python setup.py install
script: nosetests
deploy:
  provider: pypi
  user: commercehub
  password:
    secure: "GVvy0OM8RXs7yDcd9Nf6nvSQqu/8p3Dy/n3Paciv/6zKhmB9tpBicpiy2vgQiu9s6iA1BMDteE0L72mq0GbRVuS5bSAe3NBgrSCqEK9cZt3EiXAT6n/9JFhS6wd7QszC0YGh8Dyr/L2rwxWAWejyRNcwM6nD1N2m2HR1+lCaCUBX2lp1OzEgRTmL0K299VdeKOJO5+zXw7il0SrdmqC2Xqc0avoR3lkZZ52Xuh7VLhMV5U438zvq6qeUPT1pYhxWTsGlLh1WNlKyMPkaP1RUkjW7Af3z459x7WH43BKpac6HfsxvLGGbkr0ztgCN8Yul+iuNpQ3cCqIaOT9pBFR+ydAkj/AobFXgc/aNTo+NLiMGQI/UH+Q9uP5tAT8xrkmsrJuKAsBqheoTvmWVSyn4+7VHhBeHBxzizK4OX60EX3ifYvId//TmrfIz4lx5qSA9mpm/IrBjxUkNrivQyUm/7gQkb2srHdzX6PrzqzIna7+Ci79tQmAHT4WwLwmftEBTm+Dv463rny9GlAFP/5807Q3vJQlSFjq7kWPw6xLZn1OiE5Vp5NvefUC4MBsRZsV/tJwkr17jOENH2Nby3DnZXxqOx2rLI/nVPC5RxQq8Kc8JH7MQnV8UotwYvNc6bxRvPASapr4iI21npK+29dcxv7KiEERBNfiKb3AXinrR9V8="
  distributions: "sdist bdist_wheel"
  on:
    tags: true
